// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
///await Firebase.initializeApp(
   ///options: DefaultFirebaseOptions.currentPlatform,
 ///);
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfzlWMIAgdlO-8cHex3eEJtIVqDN9d9Fc',
    appId: '1:102497930084:web:dfe92686293239eb478871',
    messagingSenderId: '102497930084',
    projectId: 'unknownbank-app',
    authDomain: 'unknownbank-app.firebaseapp.com',
    storageBucket: 'unknownbank-app.firebasestorage.app',
    measurementId: 'G-H0D1FMLZP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAixUfPqztsZ-2fx_iBxp3rmbx2NBUYVc',
    appId: '1:102497930084:android:1c13b6039b2c2e11478871',
    messagingSenderId: '102497930084',
    projectId: 'unknownbank-app',
    storageBucket: 'unknownbank-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZJVdjv2ER1nSOqGzsxnQ-R-m7jANg1JU',
    appId: '1:102497930084:ios:b6064169a5789ed9478871',
    messagingSenderId: '102497930084',
    projectId: 'unknownbank-app',
    storageBucket: 'unknownbank-app.firebasestorage.app',
    iosBundleId: 'com.kasatria.unknownbank.unknownbankFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZJVdjv2ER1nSOqGzsxnQ-R-m7jANg1JU',
    appId: '1:102497930084:ios:b6064169a5789ed9478871',
    messagingSenderId: '102497930084',
    projectId: 'unknownbank-app',
    storageBucket: 'unknownbank-app.firebasestorage.app',
    iosBundleId: 'com.kasatria.unknownbank.unknownbankFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfzlWMIAgdlO-8cHex3eEJtIVqDN9d9Fc',
    appId: '1:102497930084:web:3bca5fe219301d6d478871',
    messagingSenderId: '102497930084',
    projectId: 'unknownbank-app',
    authDomain: 'unknownbank-app.firebaseapp.com',
    storageBucket: 'unknownbank-app.firebasestorage.app',
    measurementId: 'G-F9YJ4D9Q0D',
  );

}